---
name: "Sms notification"
guid: "47816a0e-e69c-44e0-ac7e-f37b134e088f"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Send sms notification"
description: >
        Sends sms notifications via selected service.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Sms.dll"
changelog: >
  changelog
